saurus:
  module:
    core:
      disabled: true
nadeo:
  service:
    core: https://prod.trackmania.core.nadeo.online
    live: https://live-services.trackmania.nadeo.live
    api: https://api.trackmania.com
  security:
    refresh-token-endpoint: /v2/authentication/token/refresh

telegram:
  bot:
    token:
    username: "SaurusTMBot"

discord:
  bot:
    token: ""

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test-saurus
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        event:
          merge:
            entity_copy_observer: allow
#        format_sql: true #
#    show-sql: true #
  security:
    oauth2:
      client:
        registration:
          tm-api:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id:
            client-secret:
          NadeoServices:
            client-id:
            client-secret:
            authorization-grant-type: client_credentials #doesn't affect provider selection
          NadeoLiveServices:
            client-id:
            client-secret:
            authorization-grant-type: client_credentials #doesn't affect provider selection
        provider:
          tm-api:
            token-uri: https://api.trackmania.com/api/access_token
          NadeoServices:
            token-uri: https://prod.trackmania.core.nadeo.online/v2/authentication/token/basic
          NadeoLiveServices:
            token-uri: https://prod.trackmania.core.nadeo.online/v2/authentication/token/basic

  liquibase:
    change-log: classpath:changelog/changelog-master.yml
#    enabled: false

logging:
  level:
    root: info
